### ISSUE TITLE
[ENH] Import with further Data

### ISSUE THREAD

**Issue by cd-FileX** [Ajatt-Tools/cropro#1]
If I am right, it should be possible to transfer notes also with duration or suspension status or similar to other profiles/decks.
If it is possible, it would be great if you could implement it. 
If I got some time left, I could also help you develop it.

\* And it would be good if this would call some kind of hook

**Comment by tatsumoto-ren** [comment]
I think it should be possible to transfer due time, type and queue of the cards that are created from a note we're importing, if that is enough for your needs.

**Comment by tatsumoto-ren** [comment]
Added a config option to copy card data when importing. Feel free to send your corrections in a PR if you need anything else.

**Comment by cd-FileX** [comment]
By the way, thank you for the quick implementation and response
