### ISSUE TITLE
Does not work with Qt5

### ISSUE THREAD

**Issue by FlaccidSnake** [Ajatt-Tools/cropro#6]
Crashes on startup with Qt5. Anki version 23.12.1. Before updating the addon last week it worked fine. Installing a Qt6 version fixes this, but other addons aren't supported. An easy fix for this would be having older versions in the github Releases page, I imagine I could put together an old version myself from the code history but I'm not that savvy.

**Comment by tatsumoto-ren** [comment]
Is it fixed now?
